#!/bin/bash
i=1
while [ $i -le 10 ]
do
  echo $i
  echo temporal$i >temp$i
  echo temporal$i.1 >temp$i.1
  echo temporal$i.2 >temp$i.2
  let i=$i+1
done

for i in {a..z}  
do
  echo $i
  echo temporal$i >temp$i
  echo temporal$i.1 >temp$i.1
  echo temporal$i.2 >temp$i.2
done

