setwd("C:/Users/pablo/Desktop/Docs/Acainfo/PREST")
load("Compilacion.Rdata")
library(DescTools) #ejecutar en consola: install.packages("DescTools")
print("Punto 1-------------------------------------------")
print(RunsTest(Compilacion$Tamano))
print("Punto 2-------------------------------------------")
print("Grafica pintada")
plot(Compilacion$Tamano, Compilacion$Tiempo)
print("Puntos 3 y 9--------------------------------------")
print(cor(Compilacion$Tiempo, Compilacion$Tamano))
print("Puntos 4 y 5 y 6----------------------------------")
modelo <- lm(Tiempo ~ Tamano, data = Compilacion)
print(summary(modelo))
print("Punto 7-------------------------------------------")
library(car) #ejecutar en consola: install.packages("car")
dev.new()
qqPlot(modelo$residuals)
print(shapiro.test(modelo$residuals))
dev.new()
plot(modelo$residuals, modelo$fitted.values)
library(lmtest) #ejecutar en consola: install.packages("lmtest")
print(bptest(modelo))
print("Punto 8-------------------------------------------")
nuevos.datos = data.frame(Tamano = 25)
print(predict(modelo, nuevos.datos, interval = c("prediction"), level = 0.99))