CREATE VIEW vista_saldo AS
SELECT
    c.DNI,
    SUM(a.BALANCE) AS "BALANCE"
FROM CLIENT c
JOIN "Cli-Acc" ca
    ON c.DNI = ca.CLIENT_DNI
JOIN ACCOUNT a
    ON ca.ING_ACCOUNT_ID = a.ID
GROUP BY c.DNI
ORDER BY "BALANCE" ASC;
