spring.application.name=springmvc-project
# Ubicación de las vistas JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Configuración de codificación
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:h2:~/h2db/crm2;MODE=LEGACY;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.hbm2ddl.auto=create
logging.level.org.hibernate=DEBUG


## Disable SpringMVC custom error page (customize in resources/static/error)
server.error.whitelabel.enabled=false

## For detailed logging during development/production: DEBUG/INFO
logging.level.org.springframework=INFO
logging.level.com=INFO

